# Build FAT filesystem header.
#
# Each flash size requires its own file system.
# mtools-n.conf defines filesystem size, and
# updfs-n.c containing fs header as a C array is generated here,
# where n is the flash size in kilobytes.
#
# The author has waived all copyright and related or neighbouring rights
# to this file and placed it in public domain.

VOLUME = "ME TEST"

export MTOOLSRC = mtools-$*.conf

SHELL = bash
NBLK = $(wordlist 2,99,$(shell sed -n 's/^.*[dr]s=/* /p' $(MTOOLSRC)))

fs-%.c: fs-%.img fs.mk
	@echo "/*" > $@
	@echo "    FAT filesystem header." >> $@
	@echo "    This file is automatically generated." >> $@
	@echo >> $@
	mdir a: >> $@
	@echo "*/" >> $@
	xxd -i $< >> $@
	@echo "unsigned int fs_$*_nblk = $(NBLK);" >> $@

fs-%.img: mtools-%.conf fs.mk
	mformat -C -d1 -r1 -v $(VOLUME) a:
	dd if=/dev/zero count=1 bs=1k of=tmp
	mcopy tmp a:me-xxxx.txt
	rm tmp
