/*
 * Contents of readme.txt.
 *
 * Copyright 2014, 2015 Mycelium SA, Luxembourg.
 *
 * This file is part of Mycelium Entropy.
 *
 * Mycelium Entropy is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.  See file GPL in the source code
 * distribution or <http://www.gnu.org/licenses/>.
 *
 * Mycelium Entropy is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "version.h"

static const char readme[] =
"                                     Hello.\r\n"
"\r\n"
"A quick guide to your Mycelium Entropy device:\r\n"
"\r\n"
"1. Plug it in.\r\n"
"2. For a 2-of-3 shared key, click the button while the LED is blinking rapidly.\r\n"
"   To get a regular wallet, do nothing.\r\n"
"3. When rapid blinking has slowed down, your new wallet is ready.\r\n"
"4. You will find a JPEG file with your new wallet; print it!\r\n"
"\r\n"
"To make more, click once for a regular wallet, or twice for a 2-of-3.\r\n"
"\r\n"
"Please allow at least 7 seconds after unplugging your Mycelium Entropy\r\n"
"before you plug it in again.\r\n"
"\r\n"
"\r\n"
"WARNING: for best security, print DIRECTLY from Mycelium Entropy.\r\n"
"\r\n"
"\r\n"
"Configuration and firmware update\r\n"
"---------------------------------\r\n"
"\r\n"
"To switch to Litecoin, uncompressed keys, or Hierarchical Deterministic wallet,\r\n"
"or to update the firmware, hold down the button while inserting the device.\r\n"
"Follow instructions in readme.txt that will appear on the device.\r\n"
"\r\n"
"\r\n"
"Error indications\r\n"
"-----------------\r\n"
"\r\n"
"3 blinks and a pause (repeating): no entropy collected.  This happens when\r\n"
"the device is plugged in too soon.  Unplug it and wait seven seconds.\r\n"
"\r\n"
"9 blinks and a pause (repeating): internal hardware error.\r\n"
"\r\n"
"The LED is lit continuously: USB communication failure.\r\n"
"\r\n"
"\r\n"
"Further reading\r\n"
"---------------\r\n"
"\r\n"
"See http://mycelium.com/entropy for the User Manual, news, support information,\r\n"
"and firmware updates (when available).\r\n"
"\r\n"
"\r\n"
"About this device\r\n"
"-----------------\r\n"
"\r\n"
"Firmware version: " VERSION
#ifdef FLAVOUR
    " (" FLAVOUR ")"
#endif
".\r\n\r\n"
"Mycelium Entropy runs Free Software and comes WITHOUT ANY WARRANTY.\r\n"
"The source code is on GitHub at https://github.com/mycelium-com/entropy .\r\n"
"\r\n"
"This device contains software distributed under the following conditions.\r\n"
"\r\n"
"Copyright 2013-2015 Mycelium SA, Luxembourg.\r\n"
"\r\n"
"Mycelium Entropy is free software: you can redistribute it and/or modify\r\n"
"it under the terms of the GNU General Public License as published by\r\n"
"the Free Software Foundation, either version 3 of the License, or\r\n"
"(at your option) any later version.\r\n"
"\r\n"
"Mycelium Entropy is distributed in the hope that it will be useful,\r\n"
"but WITHOUT ANY WARRANTY; without even the implied warranty of\r\n"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\r\n"
"GNU General Public License for more details.\r\n"
"\r\n"
"/**\r\n"
" * Copyright (c) 2013-2014 Tomas Dzetkulic\r\n"
" * Copyright (c) 2013-2014 Pavol Rusnak\r\n"
" *\r\n"
" * Permission is hereby granted, free of charge, to any person obtaining\r\n"
" * a copy of this software and associated documentation files (the \"Software\"),\r\n"
" * to deal in the Software without restriction, including without limitation\r\n"
" * the rights to use, copy, modify, merge, publish, distribute, sublicense,\r\n"
" * and/or sell copies of the Software, and to permit persons to whom the\r\n"
" * Software is furnished to do so, subject to the following conditions:\r\n"
" *\r\n"
" * The above copyright notice and this permission notice shall be included\r\n"
" * in all copies or substantial portions of the Software.\r\n"
" *\r\n"
" * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS\r\n"
" * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\n"
" * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\r\n"
" * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES\r\n"
" * OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,\r\n"
" * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\r\n"
" * OTHER DEALINGS IN THE SOFTWARE.\r\n"
" */\r\n"
"\r\n"
"/*\r\n"
" * Copyright (C) 2009-2014 Atmel Corporation. All rights reserved.\r\n"
" *\r\n"
" * Redistribution and use in source and binary forms, with or without\r\n"
" * modification, are permitted provided that the following conditions are met:\r\n"
" *\r\n"
" * 1. Redistributions of source code must retain the above copyright notice,\r\n"
" *    this list of conditions and the following disclaimer.\r\n"
" *\r\n"
" * 2. Redistributions in binary form must reproduce the above copyright notice,\r\n"
" *    this list of conditions and the following disclaimer in the documentation\r\n"
" *    and/or other materials provided with the distribution.\r\n"
" *\r\n"
" * 3. The name of Atmel may not be used to endorse or promote products derived\r\n"
" *    from this software without specific prior written permission.\r\n"
" *\r\n"
" * 4. This software may only be redistributed and used in connection with an\r\n"
" *    Atmel microcontroller product.\r\n"
" *\r\n"
" * THIS SOFTWARE IS PROVIDED BY ATMEL \"AS IS\" AND ANY EXPRESS OR IMPLIED\r\n"
" * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\r\n"
" * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE\r\n"
" * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR\r\n"
" * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\r\n"
" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\r\n"
" * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\n"
" * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\r\n"
" * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\r\n"
" * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\r\n"
" * POSSIBILITY OF SUCH DAMAGE.\r\n"
" */\r\n"
"\r\n"
"/*----------------------------------------------------------------------------/\r\n"
"/  FatFs - FAT file system module  R0.09                  (C)ChaN, 2011\r\n"
"/-----------------------------------------------------------------------------/\r\n"
"/ FatFs module is a generic FAT file system module for small embedded systems.\r\n"
"/ This is a free software that opened for education, research and commercial\r\n"
"/ developments under license policy of following terms.\r\n"
"/\r\n"
"/  Copyright (C) 2011, ChaN, all right reserved.\r\n"
"/\r\n"
"/ * The FatFs module is a free software and there is NO WARRANTY.\r\n"
"/ * No restriction on use. You can use, modify and redistribute it for\r\n"
"/   personal, non-profit or commercial products UNDER YOUR RESPONSIBILITY.\r\n"
"/ * Redistributions of source code must retain the above copyright notice.\r\n"
"/\r\n"
"/-----------------------------------------------------------------------------/\r\n"
"\r\n"
"/* Copyright (c) 2002, Alexander Popov (sasho@vip.bg)\r\n"
"   Copyright (c) 2002,2004,2005 Joerg Wunsch\r\n"
"   Copyright (c) 2005, Helmut Wallner\r\n"
"   Copyright (c) 2007, Dmitry Xmelkov\r\n"
"   All rights reserved.\r\n"
"\r\n"
"   Redistribution and use in source and binary forms, with or without\r\n"
"   modification, are permitted provided that the following conditions are met:\r\n"
"\r\n"
"   * Redistributions of source code must retain the above copyright\r\n"
"     notice, this list of conditions and the following disclaimer.\r\n"
"   * Redistributions in binary form must reproduce the above copyright\r\n"
"     notice, this list of conditions and the following disclaimer in\r\n"
"     the documentation and/or other materials provided with the\r\n"
"     distribution.\r\n"
"   * Neither the name of the copyright holders nor the names of\r\n"
"     contributors may be used to endorse or promote products derived\r\n"
"     from this software without specific prior written permission.\r\n"
"\r\n"
"  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\r\n"
"  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\r\n"
"  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\r\n"
"  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE\r\n"
"  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR\r\n"
"  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF\r\n"
"  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\r\n"
"  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\r\n"
"  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\r\n"
"  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\r\n"
"  POSSIBILITY OF SUCH DAMAGE.\r\n"
"*/\r\n";
